/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DetailsDetailsIdRouteImport } from './routes/details.$detailsId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsDetailsIdRoute = DetailsDetailsIdRouteImport.update({
  id: '/details/$detailsId',
  path: '/details/$detailsId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/details/$detailsId': typeof DetailsDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/details/$detailsId': typeof DetailsDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/details/$detailsId': typeof DetailsDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/details/$detailsId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/details/$detailsId'
  id: '__root__' | '/' | '/details/$detailsId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailsDetailsIdRoute: typeof DetailsDetailsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/$detailsId': {
      id: '/details/$detailsId'
      path: '/details/$detailsId'
      fullPath: '/details/$detailsId'
      preLoaderRoute: typeof DetailsDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailsDetailsIdRoute: DetailsDetailsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
